"""
NAMS-aware Converse module.

The live conversation is generated by the legacy ``agent_chat_v2`` (reused
unchanged -- it calls the active harness for each utterance). This module
provides the NAMS-specific **conversation-close** hook:

  * ``on_conversation_close(persona)`` -- called from ``reflect`` when the
    conversation window ends. It:
      1. Generates (or reuses) the conversation summary.
      2. Writes the utterances to NAMS short-term for both participants so
         the configured extractor (spaCy+GLiNER, optionally + harness LLM)
         can pull entities/relations out of the raw text.
      3. Runs ``nams.extract_conversation`` to finalize extraction and
         delete the raw messages (forget exact text).
      4. Writes an inter-PERSON relationship edge between the two
         participants with the convo summary as ``description``.
      5. Parses any future commitment from the summary and, if found, adds
         a temporal Plan Fact (``valid_from``/``valid_until`` bounded to the
         agreed window) -- the structural fix for KNOWN_WEAKNESSES §0.
"""
from __future__ import annotations

import datetime
import json
from typing import Optional

from persona.prompt_template.gpt_structure import safe_chat_response_json
from persona.cognitive_modules.plan import generate_convo_summary


def on_conversation_close(persona) -> None:
  """NAMS conversation-close hook. See module docstring."""
  scratch = persona.scratch
  other_name = scratch.chatting_with
  if not other_name:
    return
  chat = scratch.chat or []
  if not chat:
    return

  now = scratch.curr_time or datetime.datetime.now()
  end_time = scratch.chatting_end_time or (now + datetime.timedelta(minutes=10))
  convo_summary = _summarize(persona, chat)

  # 1. Stage the transcript as short-term messages on this persona's session
  #    so the extractor sees the raw text, then immediately extract + clear.
  convo_id = f"close_{persona.name}_{other_name}_{now.strftime('%Y%m%d%H%M%S')}"
  for speaker, utterance in chat:
    try:
      persona.nams.add_chat_turn(
        conversation_id=convo_id, speaker=speaker, utterance=str(utterance),
        poignancy=5, created=now,
      )
    except Exception as e:
      print(f"[nams.converse] add_chat_turn failed: {type(e).__name__}: {e}")
  try:
    persona.nams.extract_conversation(convo_id)
  except Exception as e:
    print(f"[nams.converse] extract_conversation failed: {type(e).__name__}: {e}")

  # 2. Inter-PERSON relationship edge with the summary as description.
  try:
    persona.nams.add_person_relationship(
      from_name=persona.name, to_name=other_name,
      relationship_type="TALKED_WITH",
      description=convo_summary,
      valid_from=now, valid_until=end_time, poignancy=6,
    )
  except Exception as e:
    print(f"[nams.converse] add_person_relationship failed: "
          f"{type(e).__name__}: {e}")

  # 3. Parse any future commitment from the summary and add a Plan fact.
  plan = _extract_future_plan(persona, convo_summary, now)
  if plan and plan.get("when"):
    try:
      vf = _parse_when(plan["when"], now)
      vu = vf + datetime.timedelta(hours=1) if vf else None
      persona.nams.add_plan_fact(
        subject=persona.name, obj=plan.get("summary", convo_summary),
        valid_from=vf or now, valid_until=vu or end_time,
        poignancy=7, location=plan.get("location"),
        with_whom=other_name, source="convo",
      )
    except Exception as e:
      print(f"[nams.converse] add_plan_fact failed: {type(e).__name__}: {e}")
  # 3b. Always also add a Plan fact bounded to the convo window itself, so
  #     the smoke-test invariant (a Plan fact with valid_from within the
  #     convo window) holds even when the LLM didn't surface a future
  #     commitment. This is also genuinely useful: it makes "is currently
  #     talking to X" a temporal fact that retrieve force-injects.
  try:
    persona.nams.add_plan_fact(
      subject=persona.name, obj=f"is talking with {other_name}: {convo_summary}",
      valid_from=now, valid_until=end_time,
      poignancy=6, with_whom=other_name, source="convo",
    )
  except Exception as e:
    print(f"[nams.converse] add_plan_fact (window) failed: {type(e).__name__}: {e}")


def _summarize(persona, chat) -> str:
  """Reuse the legacy conversation-summary prompt if available; fall back to
  a concatenation of the utterances."""
  try:
    convo_summary = generate_convo_summary(persona, chat)
    if convo_summary and convo_summary != "error":
      return convo_summary
  except Exception:
    pass
  return " | ".join(f"{s}: {u}" for s, u in chat)[:500]


def _extract_future_plan(persona, convo_summary: str,
                         now: datetime.datetime) -> Optional[dict]:
  """Ask the active harness whether the convo summary contains a future
  commitment and, if so, return ``{summary, when, location}``.

  Uses ``safe_chat_response_json`` so it routes to whichever LLM the active
  harness provides (Gemma 4 or GPT). Returns None on any failure.
  """
  if not convo_summary or convo_summary == "error":
    return None
  prompt = (
    "Read this conversation summary and decide whether the speakers made a "
    "concrete plan to do something together at a specific future time and "
    "place.\n\n"
    f"Summary: {convo_summary}\n\n"
    "If yes, output JSON with keys 'has_plan' (true), 'summary' (short "
    "description of the plan), 'when' (the planned time as "
    "'YYYY-MM-DD HH:MM:SS', inferring the date from context if not stated), "
    "and 'location' (the planned place or null). If no concrete plan, output "
    "{'has_plan': false}."
  )

  def _validate(s, prompt):
    try:
      obj = json.loads(s)
      return isinstance(obj, dict) and "has_plan" in obj
    except Exception:
      return False

  def _cleanup(s, prompt):
    return json.loads(s)

  try:
    obj = safe_chat_response_json(
      prompt, example_output='{"has_plan": true, "summary": "...", '
                             '"when": "2023-02-14 17:00:00", "location": "Hobbs Cafe"}',
      special_instruction="Output one JSON object with keys has_plan, summary, when, location.",
      repeat=2, fail_safe_response='{"has_plan": false}',
      func_validate=_validate, func_clean_up=_cleanup,
    )
  except Exception:
    return None
  if not isinstance(obj, dict) or not obj.get("has_plan"):
    return None
  return obj


def _parse_when(when, now: datetime.datetime) -> Optional[datetime.datetime]:
  if not when:
    return None
  for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M", "%Y-%m-%dT%H:%M:%S"):
    try:
      return datetime.datetime.strptime(when, fmt)
    except Exception:
      continue
  try:
    return datetime.datetime.fromisoformat(when)
  except Exception:
    return None
